name: ci-golang
on: 
  pull_request:
    branches:
      - develop
jobs:
    check-application:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            go: ['1.21', '1.23']
        name: GO TEST ${{ matrix.go }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                go-version: ${{ matrix.go }}
            - run: go test
            - run: go run math.go

